version: "3.7"

services:
  db1:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase4
      POSTGRES_USER: user4
      POSTGRES_PASSWORD: password4
    ports:
      - "5435:5432"
    volumes:
      - db1_data:/var/lib/postgresql/data
      - ./postgres-init/init-db1.sh:/docker-entrypoint-initdb.d/init-db1.sh

  db2:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase5
      POSTGRES_USER: user5
      POSTGRES_PASSWORD: password5
    ports:
      - "5433:5432"
    volumes:
      - db2_data:/var/lib/postgresql/data
      - ./postgres-init/init-db2.sh:/docker-entrypoint-initdb.d/init-db2.sh

volumes:
  db1_data:
  db2_data:
